"use client";
import { useState, useEffect } from 'react';
import Student from '@/components/du/Student';
import Teacher from '@/components/du/Teacher';
import { previewInitial } from '@/lib/du/preview';
import { stepsFor, type Level } from '@/lib/du/content';
export default function QA() { const [params, setParams] = useState<URLSearchParams | null>(null), [width, setWidth] = useState(1280), [height, setHeight] = useState(720), [kind, setKind] = useState('student'), [level, setLevel] = useState('elementary'), [n, setN] = useState(1), [slow, setSlow] = useState(false), [testStep, setTestStep] = useState(0); useEffect(() => setParams(new URLSearchParams(location.search)), []); if (process.env.NODE_ENV !== 'development')
    return <p>페이지를 찾을 수 없습니다.</p>; if (!params)
    return null; if (params.get('frame'))
    return params.get('kind') === 'teacher' ? <Teacher token="preview-local" onExit={() => { }}/> : <Student initial={previewInitial(params.get('level') || 'elementary', Number(params.get('n') || 1), Number(params.get('step') || 0))} token="preview-local" onExit={() => { }}/>; return <main style={{ padding: 15 }}><div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', marginBottom: 15 }}>{[1280, 820, 390].map(w => <button key={w} onClick={() => setWidth(w)}>{w}px</button>)}<select style={{ width: 'auto' }} aria-label="화면 높이" value={height} onChange={event => setHeight(Number(event.target.value))}>{[600, 720, 900].map(value => <option key={value} value={value}>높이 {value}px</option>)}</select><button onClick={() => setKind(kind === 'student' ? 'teacher' : 'student')}>{kind === 'student' ? '교사 화면 보기' : '학생 화면 보기'}</button><button onClick={() => setLevel(level === 'elementary' ? 'middle' : 'elementary')}>{level === 'elementary' ? '중등으로' : '초등으로'}</button><button aria-pressed={slow} onClick={() => setSlow(!slow)}>느린 저장 테스트</button>{[1, 2, 3, 4, 5].map(v => <button key={v} onClick={() => (setN(v), setTestStep(0))}>{v === 5 ? '약속·도장' : `사건 ${v}`}</button>)}<select aria-label="검수 단계" style={{ width: 'auto' }} value={testStep} onChange={event => setTestStep(Number(event.target.value))}>{stepsFor(Math.min(n, 4), level as Level).map((step, index) => <option key={step.id} value={index}>{index + 1}. {step.title}</option>)}</select></div><iframe title="기기별 화면 검수" src={`/qa?frame=1&kind=${kind}&level=${level}&n=${n}&step=${testStep}&saveDelay=${slow ? 1500 : 0}`} style={{ width, maxWidth: 'none', height, border: '1px solid #ddd' }}/></main>; }
